repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        files: \.py$

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        files: \.py$

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        files: \.py$
        
 # - repo: https://github.com/pre-commit/mirrors-pylint
 #   rev: v3.0.0a5  # or your desired version
 #   hooks:
 #    - id: pylint
 #      additional_dependencies:
 #       - pandas
 #       - numpy
 #       - matplotlib
 #       - seaborn
 #       - pytest


